### PR TITLE
Connects to #524. Replace deprecated react-tools and jstransform with Babel.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR consists of installing various Babel-related npm packages, removing the react-tools and jstransform npm packages, as well as updating other npm packages.

The following npm packages were added for `Babel` and its setup with `jest`, `browserify` and `react`:
_babel-core
babel-jest
babel-plugin-transform-runtime
babel-preset-es2015
babel-preset-jest
babel-preset-react
babel-polyfill
babel-runtime
babelify_

**Testing steps for #524:**
1. Git checkout the `524_jz_babel_conversion` branch and do a bin/buildout for the app.
2. Because switching to Babel from react-tools/JSTransform essentially impact all front-end code of the gene curation app, testing on all interface of the site is highly desirable.
3. In particular, the persona login needs to be ensured to work as expected.
4. For JavaScript testing, run `npm test` to make sure all tests pass.

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen Please revisit some of the additional dependencies that were added in package.json as we discussed and add the additional babelrc handling to not show the babel compact warning in dev:
```
"env": {
        "production": {
            "compact": "auto"
        },
        "development": {
            "compact": "false"
        }
    }
```

**Comment by jimmyzhen** [comment]
Hi @kilodalton,

I have revisited the package.json and updated the dependencies per your suggestion. We have also updated the .babelrc for the addition of the `compact` option. One extra modified file is the .eslintrc.json, in which I removed the `babel-eslint`parser.

https://github.com/ClinGen/clincoded/pull/649/files

**Comment by kilodalton** [comment]
Merged #524.

**Comment by kilodalton** [comment]
Adding comment to show closed PR on waffle (if > 7 days closed) for QA.

**Pull request merged**
