### PR TITLE
Connects to #409. Anchor added or selected PMID.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR is to address the need to differentiate the added/selected PMID on the GDM page requested in #409.

**Testing steps for #409:**
1. Go to any given GDM page and add a new PMID. Upon successfully adding the PMID and dismissing the modal box, the newly added PMID should be shown within the viewable area of the scrollable far-left column.
2. Refreshing the GDM page should show the selected PMID even after it was scrolled off the bounding viewable area.
3. From the Dashboard page, clicking on a given PMID from the "Your Recent History" list should show the selected PMID in the far-left column on the subsequent GDM page.
4. Lastly, the selected PMID is highlighted in thicker blue border to differentiate itself from the non-selected ones. To help the user to associate the selected PMID with the displayed citation and abstract in the center, the same thicker blue border is also applied to the center.

The above changes can be reviewed at:
https://409-jz-highlight-selected-pmid-363a23d-jzhen.demo.clinicalgenome.org

### CODE REVIEW

**Comment by wrightmw** [comment]
@jimmyzhen  All 4 testing steps worked well for me. Great!

**Comment by jimmyzhen** [comment]
@wrightmw, thank you!

**Comment by selinad** [comment]
A bit late, but they all worked great for me as well!

**Comment by kilodalton** [comment]
Merged #409.

**Pull request merged**
