### PR TITLE
Connects to #24 Curator demo page

### PR DESCRIPTION
**Pull request by forresttanaka**
This branch has a working curator demo page at the curator path, and a document describing how to bring up more pages like this using a temporary templating system.

I notice one font sizing bug that only affects Chrome, and not Firefox nor Safari. When the page initially loads, the font size is too large in Chrome. If you resize the browser to mobile size, then resize it back, the font size becomes proper. I’ll try to fix that for tomorrow. If you’d prefer to wait for that before merging this PR, that’s fine.

### CODE REVIEW

**Comment by kilodalton** [comment]
@forresttanaka Do you have a handle on what is required to fix the Chrome font size bug?

**Comment by forresttanaka** [comment]
Not yet. I have some ENCODE to work on in the morning, and will try to figure this out after.

**Comment by forresttanaka** [comment]
Font problem is fixed (following the way Zurb Foundation does it), and fixed a ReactJS console warning message I hadn’t noticed.

**Comment by kilodalton** [comment]
Connects to #24

**Pull request merged**
