### PR TITLE
Connects to #295 ft node4

### PR DESCRIPTION
**Pull request by forresttanaka**
#### From Travis-CI output

```
$ nvm install 4
######################################################################## 100.0%
Checksums empty
Now using node v4.2.1
before_install.6
0.00s$ node --version
v4.2.1

Using Jest CLI v0.5.10
 PASS  libs/__tests__/origin-test.js (0.013s)
 PASS  libs/__tests__/registry-test.js (0.646s)
 PASS  components/__tests__/server-render-test.js (19.02s)
3 tests passed (3 total)
Run time: 22.338s
```

#### From EC2 spinup output

```
jest-cli@0.5.10 node_modules/jest-cli
├── jasmine-pit@2.0.2
├── object-assign@4.0.1
├── graceful-fs@4.1.2
├── node-worker-pool@3.0.2
├── diff@2.1.3
├── coffee-script@1.10.0
├── json-stable-stringify@1.0.0 (jsonify@0.0.0)
├── lodash.template@3.6.2 (lodash._reinterpolate@3.0.0, lodash._basecopy@3.0.1, lodash._basevalues@3.0.0, lodash.restparam@3.6.1, lodash._basetostring@3.0.1, lodash.templatesettings@3.1.0, lodash._isiterateecall@3.0.9, lodash.escape@3.0.0, lodash.keys@3.1.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── which@1.2.0 (is-absolute@0.1.7)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── jasmine-only@0.1.1 (coffee-script@1.6.3)
├── resolve@1.1.6
├── sane@1.3.0 (watch@0.10.0, minimist@1.2.0, minimatch@0.2.14, exec-sh@0.2.0, fb-watchman@1.6.0, walker@1.0.7)
├── cover@0.2.9 (which@1.0.9, underscore@1.2.4, underscore.string@2.0.0, cli-table@0.0.2)
├── node-haste@1.2.8 (esprima-fb@4001.1001.0-dev-harmony-fb)
├── jsdom@6.5.1 (acorn-globals@1.0.6, xmlhttprequest@1.8.0, xml-name-validator@2.0.1, browser-request@0.3.3, xtend@4.0.0, symbol-tree@3.1.3, tough-cookie@2.2.0, nwmatcher@1.3.6, cssom@0.3.0, parse5@1.5.0, whatwg-url-compat@0.6.5, acorn@2.4.0, escodegen@1.7.0, htmlparser2@3.8.3, request@2.65.0, cssstyle@0.2.29)
└── istanbul@0.3.22 (async@1.4.2, abbrev@1.0.7, wordwrap@1.0.0, nopt@3.0.4, esprima@2.5.0, supports-color@3.1.2, once@1.3.2, fileset@0.2.1, escodegen@1.7.0, handlebars@4.0.3, js-yaml@3.4.3)
```

### CODE REVIEW

**Comment by forresttanaka** [comment]
```
$ node --version
v4.0.0
$ npm --version
2.14.2
```

**Comment by kilodalton** [comment]
Merge is on hold for a few days while we work on production release.

**Comment by kilodalton** [comment]
@forresttanaka How would you feel about jumping right to node5 instead? https://nodejs.org/en/

**Comment by forresttanaka** [comment]
From a purely selfish point of view, I'd like to go with the version that means I don't have to switch node versions between ClinGen and ENCODE.

But I was reading about that, and wondered if the next version we should all go to is node 6 since that'll be the next one with the long support path. I don't really know the right answer.

**Comment by forresttanaka** [comment]
Node 5 moves to npm 3. I’d like to see how that hits us too. That I think makes Node 5 both more and less attractive. I’ll look into that this morning.

**Comment by kilodalton** [comment]
Adding on to that, for information's  sake, brew install node already installs node5 by default. So we if we stick to 4 we would be in the position of holding the line again on future development (including npm).

**Comment by forresttanaka** [comment]
Ah thanks. I was minutes away from checking which version brew install installs.

**Comment by kilodalton** [comment]
Merged #295.

**Pull request merged**
