### PR TITLE
Connects to #34 kd initial tests

### PR DESCRIPTION
**Pull request by kilodalton**
Many tests were removed or changed (i.e. update with clincoded references) to order to get a baseline of an initial set of tests that would all pass with the current repo. Notable among these is that create_mapping is disabled in  testing_indexing test teardown, some test_indexing methods are commented out, and "from ..loadxl import ORDER" temporarily changed to use a static fixed list in test_views.py.  

To test: 

Pyramid tests:   ` bin/test -m "not bdd"`
--230 passed, 4 deselected in 70.70 seconds

BDD tests:   `bin/test -m bdd -v -v`
--4 passed, 230 deselected in 20.40 seconds

Javascript tests:   `npm test`
--4 tests passed (4 total)

### CODE REVIEW

**Comment by kilodalton** [comment]
@forresttanaka Can you please review this branch (34_kd_initialTests) and make sure all the tests run as indicated above)?

**Comment by forresttanaka** [comment]
I’ll get started on that now.

**Comment by forresttanaka** [comment]
Looks really good!

Local Travis CI: ```bin/test -v -v```
—234 passed in 98.21 seconds

Pyramid tests: ```bin/test -m "not bdd"```
—230 passed, 4 deselected in 79.51 seconds

BDD tests: ```bin/test -m bdd -v -v```
—4 passed, 230 deselected in 22.45 seconds

Javascript tests: ```npm test```
—4 tests passed (4 total)
—Run time: 7.894s

**Comment by kilodalton** [comment]
Merged #34

**Pull request merged**
