### PR TITLE
Connects to #322. Connects to #475. Connects to #613. Connects to #622. Connects to #629. Assessment Issues

### PR DESCRIPTION
**Pull request by kgliu0101**
**Changes for tickets #475 and #622**
  1. In family page, add a note to indicate that assessing a segregation is not allowed since no segregation data entered.
  2. Add a note to indicate that assessing family/segregation or experimental is not allowed since the evidence has been not assessed by its owner.
  3. Add existing assessment info in family, experimental and variant curation/edit and view pages.
Code change in family_curation.js, experimental_curation.js, variant_curation.js and assessment.js

**Change for ticket #629 (Bug of assessing family without segregation data)**
  1. Add control code in assessment.js to force assessment selection change to Not Assessed when all segregation data is deleted.
  2. Edit code to not count value "Not Assessed" as a valid assessment.

**Test of Family/Segregation Assessment**
* Create a new GDM and add a PMID.
* Generate a new family, expect to see a new note before enter segregation.data.
screen shot 2016-03-14 at 12 39 04 pm

* Enter any segregation field and expect to see:
screen shot 2016-03-03 at 12 49 59 pm

* Delete entered data, expect to see the note and disabled assessment selection again.

* Save the family without segregation data. Open view page and expect to see the note and assessment selection disabled as:
screen shot 2016-03-14 at 12 37 00 pm

* Logout and login as 2nd user. View the family and expect to see another note and disabled selection.
screen shot 2016-03-04 at 12 15 59 pm

* Logout and login as the 1st user. Edit family to enter segregation data  but not assess it and save. Logout and login as 2nd user. View the family and expect to see the same " ... not yet assessed on it." note and disabled selection.
screen shot 2016-03-03 at 12 53 08 pm

* Logout and login as 1st user. Assess the family to Supports and save. Logout and login as the 2nd user and view the family. Expect to see the owner's assessment and to be able to assess the family.
screen shot 2016-03-03 at 12 55 23 pm

* Select Contradicts and save. Open the family view page again and expect to see all assessments info from both 1st and 2nd users.
screen shot 2016-03-03 at 12 58 42 pm

**Test of Experimental Assessment**
* Login as the 1st user.
* Create a new experimental, not assess it and save. Logout and login as 2nd user, view the experimental. Expect to see the "... not yet assessed on it." note and disabled selection.
screen shot 2016-03-04 at 9 48 39 am

* Logout and login as the 1st user. Assess the experimental to Supports and save. Logout and login as 2nd user, view the experimental and expect to be able to assess.
screen shot 2016-03-04 at 9 55 34 am

* Assess to Contradicts and save. Open the view page again and expect to see assessment info of both users.
screen shot 2016-03-04 at 9 57 06 am

**Test of Variant Assessment**
* Login as the 1st user.
* Associate a variant to the family. Curate the variant and assess it to Supports, save. Logout and login as 2nd user. Curate the variant and assess as Contradicts, save. Logout and login as 3rd user. Curate the variant and expect to see assessment info of both 1st and 2nd users.
screen shot 2016-03-04 at 10 13 32 am

**Test of Ticket #629**
*  Bug of assessing family without segregation data
    * Curate a family, enter a segregation and select assessment to Supports.
    * Delete entered/selected data in all segregation fields. Expect to see Assessment selection value changing to Not Assessed.
  * Save and open edit family page, expect to see opened segregation input fields, Assessments: None, "... segregation data has been entered." note and Not Assessed selection.
screen shot 2016-03-14 at 10 13 25 am
* Enter some segregation data and assess it to Review, save. Open family view page, expect to see:
screen shot 2016-03-14 at 12 58 20 pm

* Handling assessment Not Assessed
    * Assess any evidence and save.
    * Change to Not Assessed, expect to see None at Assessments panel.
screen shot 2016-03-04 at 4 10 08 pm

**End of Test**

### CODE REVIEW

**Comment by kilodalton** [comment]
@kgliu0101 

A few bugs remain:

If the first curator has not assessed on the data, the second curator should not see this message...but currently they do: "The option to assess segregation is not available until some segregation data has been entered."

Second curator viewing family that has not been assessed:
image

The second curator should only see the message about not being able to assess until the creator has assessed.

Additionally, if I go back to edit my family page, although I am the first creator I see this on the family page:

image

**Note that I have no family segregation data, but I do somehow still have an assessment of Supports, but I can't edit the segregation data because I have an assessment!**

**Comment by kgliu0101** [comment]
@kilodalton 

I could not repeat these bugs in my machine, tried many time under different conditions. Would you please show me your steps to get them?

**Comment by kilodalton** [comment]
@kgliu0101 
**Steps to reproduce the bug:**
* Create GDM -> +PMID
* Create Family, following the steps below:
  * In the "Family -- Segregation" section add anything to one of the fields (e.g. `test` to `Additional Segregation Information:` box)
  * In the "Family -- Segregation Assessment" section, change `Assessment:` to `Contradicts`
  * **BEFORE SAVING** remove any data in in the "Family -- Segregation" section
  * The `Assessment:` list should now automatically show `Not Assessed` and you should not be able to change the assessment
  * **Save** the family
* After Saving, click on the Edit/Assess button next to the family name...you should see this (no segregation data saved + a Contradicts asseessment + inability to edit segregation data):
image


It appears that although the dropdown display switches to "Not Assessed" when segregation data is removed it actually does not update the **value** of that selection and incorrectly creates an Assessment which blocks further action.

A second curator then incorrectly sees this for that same record:
image

(when they should be seeing this:)
image

**Comment by kgliu0101** [comment]
@kilodalton 

I edited related handling codes. Give a test again at new version of branch (3b3d5d1).

**Comment by kgliu0101** [comment]
@kilodalton 

I have gone through the test steps successfully. It's ready.

**Comment by kilodalton** [comment]
Connects to #322. Connects to #475. Connects to #613. Connects to #622. Connects to #629.

**Pull request merged**
