### PR TITLE
Connects to #669. Connects to #668. Connects to #670. Connects to #675. Select variant page and related modals

### PR DESCRIPTION
**Pull request by mrmin123**
This PR contains code for the new select-variant page, the add external resource modals associated with that page (ClinVar and CAR), and parsing of data from those resources.

* The add external resource modal code has been extracted from `curator.js` to `add_external resource.js`. References have been fixed in GCI pages that previously used the add external resource modal
* The new select variant page has been created as  `select-variant.js`. Relevant CSS has been added to `_form.scss` and `_curator.scss`
* `parse-resource.js` has all the code for parsing data from ClinVar and CAR and conforming it to our schema

Testing:
* Confirm that link to select-variant page exists on dashboard
* On select-variant page, try adding a variant via the ClinVar modal and the CAR modal
* Confirm that the variant object was properly created in internal db
* On pressing 'View Variant' page, browser should be taken the `/curation-variant/?variant=[UUID]` (page does not exist yet)
* Confirm that the add ClinVar variant modal works in GCI

### CODE REVIEW

**Comment by kilodalton** [comment]
@mrmin123:
Display issue:
The items in the page after selecting and saving a ClinVar ID seem to be not aligned properly:
[http://localhost:6543/select-variant/](http://localhost:6543/select-variant/)

image

**Comment by mrmin123** [comment]
As this is a first-pass integration things are not perfect/still being worked out.

Additional points that need work are in tickets #681 and #682

**Comment by mrmin123** [comment]
@kilodalton the display on that page will be made defunct by changes in #681

**Comment by kilodalton** [comment]
Will be handled in #682 (update variant handling from CAR):
Retrieving a CAR ID that is not in CAR causes modal to stall (because of the 404). @mrmin123 says this will be addressed in #682 (update variant handling from CAR)

Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 XMLHttpRequest cannot load http://reg.genome.network/allele/CA001234. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:6543' is therefore not allowed access. The response had HTTP status code 404.

More display issues on the returned info on modal and select variant page...:

image

The HGVS identifier should have a bullet point or something in front of it if it will be right indented. 

image

Buttons should probably be right aligned...visually doesn't seem right.


Making a note here for tracking that #681/#682 should address the display and error handling.

**Comment by mrmin123** [comment]
Updated so that the variant select endpoint is to `/variant-central/?variant=[UUID]`

**Comment by kilodalton** [comment]
Merged #669. Merged #668. Merged #670. Merged #675.

**Pull request merged**
