### PR TITLE
Connects to #997 kl edit schema for summary

### PR DESCRIPTION
**Pull request by kgliu0101**
This PR has schema changes for summary page. There is no change at UI or logic involved.

**Code Changes**
 1. Add a non-required data property `markAsProvisional` in file `src/clincoded/schemas/interpretation.json`.
 2. Remove `enum` from property `autoClassification` and property `autoClassification`in file `src/clincoded/schemas/provisional_variant.json` to allow taking new type of classification.
 3. Edit test data files `src/clincoded/tests/data/inserts/interpretation.json` and `src/clincoded/tests/data/inserts/provisional_variant.json` to match the schema changes.

**Test**
* Go to [http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4/](http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4/) and expect top see `"markAsProvisional": false,` in the interpretation object as below.
screen shot 2016-09-14 at 4 15 06 pm

* Go to [http://localhost:6543/provisional-variant/a9886cb9-cea3-4372-8d2b-845563b47b1f/](http://localhost:6543/provisional-variant/a9886cb9-cea3-4372-8d2b-845563b47b1f/) and expect to see `"autoClassification": "Uncertain significance - conflicting evidence",` in provisional_variant object as below.
screen shot 2016-09-14 at 4 17 08 pm

**End of Test**

### CODE REVIEW

**Comment by kilodalton** [comment]
@kgliu0101 I am going to move this along for the sake of time. but typically the `markAsProvisional` would not include a verb (i.e. `mark`) in the field name. It's a status like `curatorProvisionalStatus`.

**Comment by kilodalton** [comment]
Merged #997.

**Comment by kgliu0101** [comment]
@katerose Thank you. I'll change it later.

**Comment by kilodalton** [comment]
[pls ignore: comment added only to refresh PR display on waffle]

**Comment by jimmyzhen** [comment]
The provided test steps are not applicable for testing on the release candidate as the UUIDs would be hard to replicate.

However, the changes to the schema can be validated in my experience on creating the summary page. Moving this ticket to Release Ready.

**Pull request merged**
