### PR TITLE
Connects to #204 kd add users

### PR DESCRIPTION
**Pull request by kilodalton**
Dashboard currently uses first element of group to display role. "ClinGen Curator", if used as the first element in that group, will be displayed on dashboard. If "admin" is kept in the group list for that user then admin permission is retained although the display name has changed.

A better implementation of this in the future would have groups in user object (which are actually "roles" used for security purposes, etc) be entirely separate from display name. There should be some globally accessible object that maps role to display name outside of the user object.

image

--added new curators to users
--add "ClinGen Curator" to curator's groups
--created a sample "curator lab" object (not sure if we will need lab objects in the future)
--updated test and test+gene+disease backup

### CODE REVIEW

**Comment by mrmin123** [comment]
@kilodalton Changes look good, and the new users are being loaded properly. I agree that we should eventually move user group properties out of the user objects. Perhaps we can re-purpose the Labs object if it's not being used for anything else.

**Comment by kilodalton** [comment]
We do need to keep groups there to set permissions on the user. But we should separate out what the display should be for each role specified in groups.

**Comment by kilodalton** [comment]
Merged #204

**Comment by selinad** [comment]
Hi Karen,

Looks really good.  The only small thing is that there is some redundancy with the word curator.

Would it work to say "Your status: ClinGen Curator"

I think this works well as I am not sure whether reviewers will have the term curators in the name (e.g. Expert Curator or Expert Reviewer)

**Comment by kilodalton** [comment]
No problem. I have already merged that code. I'll make another tiny ticket to change the text preceding the job title to say "Your status:"  instead of "Your curator status:".

**Pull request merged**
