### PR TITLE
Connects to #238. Add new Recent History items to Dashboard

### PR DESCRIPTION
**Pull request by mrmin123**
Supports Group and Family additions in Recent History:

image

(any strange sorting you may see (should) have been addressed by #252)

### CODE REVIEW

**Comment by kilodalton** [comment]
@mrmin123 I created a GDM, added PMID to that GDM, then added a group to PMID. The group addition should be last item added, but is in center in history list:

image

I realize they are close in time, we should have enough granularity on timestamps to get the specific order correctly. Can you take a look?

**Comment by mrmin123** [comment]
@kilodalton this should be addressed by #246 
You're seeing the weird ordering not because the sorting is incorrect, but because the annotation's `date_created` value is being incorrectly updated when a new family/group is created:
image

**Comment by mrmin123** [comment]
@kilodalton to clarify on the above screenshot: the annotation object's `date_created` should match the article object's `date_created`, but it's been updated after the creation of the group object, 2 minutes later. This causes the PMID added action to be 'newest' in the recent history list.

**Comment by forresttanaka** [comment]
I added https://github.com/ClinGen/clincoded/issues/259 after talking with @kgliu0101. Any time an object in a GDM’s hierarchy gets changed for whatever reason (adding a PMID, editing a group, adding an individual to a family, etc), the GDM has to be written to the DB so that its last_modified time gets updated, even if nothing in the GDM object itself changes. That way, when you add a group as @kilodalton did above, the GDM’s last_modified time will change even though only the annotation object was modified.

**Comment by mrmin123** [comment]
#261 has fixed the annotation date change issue on the dashboard:
image

**Comment by kilodalton** [comment]
Merged #238

**Comment by selinad** [comment]
This looks good!

**Pull request merged**
