### PR TITLE
Connects to #634. Connects to #638. Label styling, PMID sorting

### PR DESCRIPTION
**Pull request by mrmin123**
#### Related to #634:

Testing:

1. Add PMID with lower-case first-letter of last name (21217753)
2. Add PMID with upper-case first-letter of last name (19711971)
3. Confirm that sorting in the PMID list is case-insensitive

image

#### Related to #638:

Testing:

1. Add Group, Family, Individual, Experimental Data, and Variants with very very long names
2. Confirm that the labels cutoff properly in the Curation Palette (both labels and associations), Variation Header, and Dashboard

image
image
image
image

### CODE REVIEW

**Comment by kilodalton** [comment]
@mrmin123 Re: case-insensitive sorting for #634. 
This is not working as expected:
image

PMID list shows in this order (note: only "van de Laar" sorts properly *before* "Zaima"... it seems as if the rest is sorting in reverse sort order [Z->A]): 
- 21217753 van de Laar IM et al. 
- 19711971 Zaima K et al.
- 26653405 VanderWeele TJ
- 26503034 Valeri L et al.
- 10000 Baumstark JS et al.

**Comment by kilodalton** [comment]
@mrmin123  Re #638 Fix overhanging labels on curation palette:
Long Group, Family, Individual, Experimental Data, and Variant names do not wrap appropriately on View+Edit pages. Please advise whether you would prefer to add that to this ticket or address in a separate ticket:

example:
narrow window
image

wider window
image

Note: grey bar to the right indicates edge of browser window which was included to show text is cut off

**Comment by mrmin123** [comment]
@kilodalton oops alphabet is hard. Fixed the sorting:
image

I'm also going to fix the displays on View and Edit pages in this PR. @wrightmw and I agreed that most of the issue would be solved by implementing a character limit (#640), but on hindsight I can see this still being an issue with narrow windows/resolutions. Will notify you when it's ready.

**Comment by mrmin123** [comment]
@kilodalton @selinad @wrightmw This is how the ellipsis work for the View and Edit pages, let me know if they look ok/if you want things changed:

image
image
image
image
image
image
image
image

**Comment by selinad** [comment]
Thanks, @mrmin123 - I think we could have a much smaller character limit?  I would think 50-60.  It's meant to be a label, not a description.... @wrightmw what do you think?

**Comment by mrmin123** [comment]
@selinad The character limit discussion should take place in #460... I implemented the ellipsis for overflow mainly for narrow windows (perhaps I should have provided screenshots of narrow windows), where even a shorter name might be longer than the window width:

image

**Comment by selinad** [comment]
Hi @mrmin123 this all looks good!  Thank you!

**Comment by kilodalton** [comment]
@mrmin123 after creating long variant name on Experiment:
image

Will make a note in #640 that the page after initially saving/creating an item needs to be checked for G/F/I/E too.

Otherwise all is OK.

**Comment by kilodalton** [comment]
Merged #634. Merged #638.

**Comment by kilodalton** [comment]
Adding comment to show closed PR on waffle (if > 7 days closed) for QA.

**Pull request merged**
