### PR TITLE
Connect to #262 kl variant pathogenicity, mode code and provisional

### PR DESCRIPTION
**Pull request by kgliu0101**
Summary of changes.
* Add pathogenicity schema and test data. Change relevant inside sub-object to an array in gdm and edit handling scripts. Type url ../pathogenicity to view all pathogenicity test data. Type url ../gdm and select a gdm with pathogenic data to view embedded pathogenic data.
* Add a new property "modeCode" in gdm, related to ticket #235. Type url ../gdm and select a gdm to view test data.
* Add a new object "provisionalClassification", related to ticket #96. Add its link in gdm. Add/edit relevant test data files.
Type url ../provisional to view provisional test data. Type url ../gdm and select a gdm with provisional classification to view embedded.
* Add new properties in object assessment to store gdm and evidence info. Edit relevant test data.
* Add calculated properties in annotation and edit its "columns" to show numbers of group, family, individual and experimental included. UI should NOT be influenced.
* Add property "active" with default value "true" in article, group, family and individual. UI should NOT be influenced.
* Move "last_modified" on top of "date_created" in schema mixins.json to try to make "last_modified" not earlier. (The bug still exists according to Karen's test. A new ticket will be created to solve it).
* Upload new dump files.
* Testing at local by successfully creating a new gdm, adding/editing an OMIM, adding a  pmid, adding/viewing/editing a group, adding/viewing/editing a family to the group and adding/viewing/editing a family directly with pmid. "last_modified" is not earlier than "date_created" in all of them.
curation

### CODE REVIEW

**Comment by kgliu0101** [comment]
* To view pathogenicity test data: type url ../pathogenicity.
* To view embedded pathogenicity in gdm: type url ../gdm and select a gdm with pathogenic data.
* To view property "modeCode" in gdm: type url ../gdm and select a gdm.
* To view provisional test data: type url ../provisional.
* To view embedded provisional in gdm: type url ../gdm and select a gdm with provisional classification.

**Comment by kilodalton** [comment]
To view test data
* Type url ../pathogenicity to view all pathogenicity.

http://localhost:6543/pathogenicity/

* Type url ../gdm and select a gdm with pathogenic data to view embedded pathogenicity in gdm.

From test data:
http://localhost:6543/gdm/9ffd7c1e-16d9-11e5-b283-60f81dc5b05a/

* Type url ../gdm and select a gdm to view property "modeCode".

`"modeCode": "0",` is set for all created GDMs
(go to `URL/gdm/<uuid>/?format=json`)

* Type url ../provisional to view all provisional data.

http://localhost:6543/provisional/

* Type url ../gdm and select a gdm with provisional classification to view embedded provisional in gdm.

From test data:
http://localhost:6543/gdm/9ffd7c1e-16d9-11e5-b283-60f81dc5b05a/





@kgliu0101 
--Can you explain why you added modeCode (which defaults to 0, so all new gdms have a value of "0") is added to all new GDMs? Is this related to another ticket?

--date_created and last_modified are still incorrect:
Example:
2 different gdms...in both cases last_modified is before date_created:
"last_modified": "2015-08-31T19:57:21.205401+00:00",
"date_created": "2015-08-31T19:57:21.205414+00:00",

"last_modified": "2015-08-31T19:59:18.110748+00:00",
"date_created": "2015-08-31T19:59:18.110761+00:00",

**Comment by kgliu0101** [comment]
Adding an internal code for Mode of Inheritance is related to ticket #235. Corresponding 16 options in Mode of Inheritance list, new gdm will have the value (1 to 16) if passed from or a default 0 if no passed. Relevant UI change is not necessary at this moment until mechanism for searching gdm by gene-orphaNumber-modeCode is required.

**Comment by kgliu0101** [comment]
Correct "last_modified" is related to ticket #259

**Comment by kilodalton** [comment]
@kgliu0101 As we discussed, the last_modified date should *not* ever be *before* the date_created timestamp. It should be *equal* to or *after* date_created. However, for brand new gdm objects the last_modified is still before the date_created.

**Comment by kilodalton** [comment]
Merged
#262 -- Separate variant pathogenicity as independent object in schema
#235 -- Add internal code for model in gdm
#96 -- Model Summary and Provisional Assertion

**Pull request merged**
