### PR TITLE
Connects to #712 kl schema, assessment in individual, LOD in segregation, molecular consequence in variant

### PR DESCRIPTION
**Pull request by kgliu0101**
**Changes in Schema Files** in dir `src/clincoded/schemas/`
1. Added property "assessments" in file `individual.json`
2. Added property "lodScore" to sub-object "segregation" in file `family.json`
3. Added properties "variationType" and "molecularConsequenceList" in file `variant.json`

**Changes in Test Data** in dir `src/clincoded/tests/data/inserts/`
1. Created a new assessment in file `assessment.json` and added its uuid to Individual BBB in file `individual.json`
2. Added segregation LOD scores to FamilyCCC and FamilyRousseau in file `family.json`
3. Added variation type data and molecular consequence data to variants, if available on ClinVar , in file `variant.json`

**Changes** in file `src/clincoded/types/__init__.py`
1. Added function to set reverse link from assessment to individual.
2. Added functions to display source, variation type and molecular consequence of variant.

**Other Change**
Created new dump files

**View Test Data**
[http://localhost:6543/families/e659bd3a-18f8-11e5-9d3a-60f81dc5b05a/?format=json](http://localhost:6543/families/e659bd3a-18f8-11e5-9d3a-60f81dc5b05a/?format=json) to view LOD score in family/segregation
[http://localhost:6543/individuals/6f762e73-1910-11e5-998f-60f81dc5b05a/?format=json](http://localhost:6543/individuals/6f762e73-1910-11e5-998f-60f81dc5b05a/?format=json) to view assessment in individual
[http://localhost:6543/variants/](http://localhost:6543/variants/) to view variation type and molecular consequence in variant

### CODE REVIEW

**Comment by kilodalton** [comment]
@kgliu: do not ellipsize returned content in the python code… e.g. your changes in  `src/clincoded/types/__init__.py` to truncate clinvarVariantTitle

You will note that we already have strategies to handle long labels/titles throughout the application in our JS and [S]CSS.

**Comment by kilodalton** [comment]
@kgliu0101 Please fix the typo "Variant Representive” in multiple places. Did you mean "Variant Representation"? Possibly you may want to change `represent` to something more like `variant_identifier`at this time as well.

**Comment by kgliu0101** [comment]
@kilodalton It's changed.

**Comment by kilodalton** [comment]
Merged #712.

**Pull request merged**
