### PR TITLE
Connects to #903. Connects to #904.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR primarily consists of changes pertinent to:
1) Fixing the bug in which the Ensembl link does not persist if the user navigates to other tabs and returns to the Gene-centric tab (#903).
2) Adding the list of synonyms under **HGNC** in the Gene Resources panel on the Gene-centric tab (#904).

Additional changes:
1) Fixing a bug that causes script execution and UI display to fail when there is no ExAC data included in the MyGene.info response (https://github.com/ClinGen/clincoded/issues/883#issuecomment-240560839).
2) Minor text change in data source attribution (https://github.com/ClinGen/clincoded/issues/800#issuecomment-240558170).

**Steps to test:**
1. Login and use **CA501097** CAR ID to select variant.
2. Click through all the tabs and back to the Gene-centric tab. Expect to see no unexpected UI display even when there is no ExAC constraint score data available.
3. Expect to see the display of Ensembl gene_id link to persist on the Gene-centric tab even after clicking through other tabs.
4. Expect to see the "When available, data in this table was retrieved..." wording in the attribution text at the bottom of the tabs.
5. Now change to **231744** variant id and proceed to the Gene-centric. Expect to see the display of synonyms under **HGNC**, due to the gene being available in the test data.

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen There was a merge conflict with dev so I pulled in dev and updated  `/src/clincoded/static/components/variant_central/interpretation.js` so I could merge the PR

**Comment by kilodalton** [comment]
Merged #903. Merged #904.

**Comment by jimmyzhen** [comment]
Thanks, @kilodalton!

**Comment by selinad** [comment]
Works!  So nice!

**Pull request merged**
