### PR TITLE
Connects #427 kl homozygous

### PR DESCRIPTION
**Pull request by kgliu0101**
**Changes:**
- Add a new property "genotype" (non-required) in schema individual.json for storing item "Mode of Inheritance" in interface.
- Add handling codes in family_curation.js, individual_curtion.js and curator.js to:
  1.  add a pull-down list in interfaces for the new field titled Mode of Inheritance;
  2.  enable/disable variant fields;
  3.  control error messages;
  4.  control submission;
  5.  display genotype (Mode of Inheritance) in view pages;
  6.  assign genotype value to pre-R4 product data and let user edit later.

**Test for Creating/Editing/Viewing Individual**
- Create a GDM and add PMID 123;
- Add an individual, Ind001, select No at proband, expect to see Mode of Inheritance field in variant panel like:
summary
- Select "Dominant", expect to see required VariationID and Other description fields for one variant like:
summary
- Change Mode of Inheritance to "Compound Heterozygous", expect to see fields for 2 variants.
summary
- Click Save without entering data in any variant field, expect to see error messages under each of the fields as:
summary
- Go back to "No Selection" at Mode of Inheritance, expect to see all error messages cleared.
- Select "Compound Heterozygous" and click Save again, after error messages displayed, change Mode of Inheritance value to "Homozygous Recessive", expect to see fields for the one variant only (with error message).
summary
- Enter variation id 111, expect to see error messages cleared and Other description field disabled as:
summary
- Click Save and expect save the individual successfully.
- Go to curation central page and click View Ind001. Expect to see variant info as:
summary
- Go to curation central page and click Edit Ind001.
- Change Mode of Inheritance value to "Compound Heterozygous" and enter "NM_000527.4:c.1467C>G" in Other description field of the 2nd variant, click Save.
- Expect edit the individual successfully.
- Go to curation central and view the individual, expect to see new genotype (Mode of Inheritance) and variant data as:
summary
- Edit Ind001 again and select "No Selection" at Mode of Inheritance, click Save.
- View Ind001 and expect to see "No variant associated." in Associated Variant(s) panel.
summary

**Test for Creating/Editing/Viewing Family**
- Add family Family010 to the PMID, select genotype value "Dominant", enter variant 222, then expect to trigger proband fields shown as:
summary
- Click Save without enter proband data, expect to see error messages like:
summary
- Change Mode of Inheritance to "No Selection", expect to see no variant field displayed and clear error messages.
- Select "Dominant", associate variant 222, name proband Ind011 and enter a Orphanet id, and lick Save, expect to save the family successfully.
- View Family010 and expect to see genotype value (Dominant) and variant id (222).
summary
- View Ind011, expect to see the same genotype value and variation id.
- Edit family010, change Mode of Inheritance value to "No Selection", click Save, expect to see error message as:
screen shot 2016-02-05 at 12 45 52 pm
- Change  to any other option, expect to see the error messages cleared.
- Select option "Compound Heterozygous", expect to see data fields for the 2nd variant.
- Click Save without entering any thing in the fields, expect to see error messages.
summary
- Enter variation id 333 for the 2nd variant and click Save again, expect to save the family successfully.
- View Family010 and expect to see "Compound Heterozygous", variationID 222 and variationID 333.
- View Ind011 (proband) and expect to see the same genotype and variation IDs.

**End of Test**

### CODE REVIEW

**Comment by kilodalton** [comment]
@kgliu0101 
In the testing steps it says
"Edit family010, click Genotype selection, expect not to see "No Selection" in Genotype pull-down list because of proband existing (currently all variants are able to be removed from family and its proband)."

Actually "No Selection" is still available in the dropdown list, and if you select it and try to save you get a spinning save button and an error in the console...
image

Everything else works as expected. Can you look into suppressing the  "No Selection" option?

**Comment by kgliu0101** [comment]
@kilodalton Checked in current product version, it's possible to delete variant from a family and its proband. Even I don'd think it make sense, we'd better let Selina and Matt decide. So, I just removed this part from testing steps. Thank you.

**Comment by kilodalton** [comment]
@kgliu0101 Since it causes a blocking error on the site, just removing it from the testing steps doesn't solve the problem.

The No Selection option must be suppressed in this case (family has proband with variant).

**Comment by kilodalton** [comment]
@kgliu0101 Or alternatively it must show an error and prevent submit with the appropriate error message when user selects Save in that case.

**Comment by kgliu0101** [comment]
Error message.
screen shot 2016-02-05 at 11 50 42 am

**Comment by kgliu0101** [comment]
Edit the message as:
screen shot 2016-02-05 at 12 31 41 pm

**Comment by kgliu0101** [comment]
This one.
screen shot 2016-02-05 at 12 45 52 pm

**Comment by kilodalton** [comment]
@kgliu0101 Perfect.

**Comment by kilodalton** [comment]
After discussion with @selinad and @kgliu0101:
Curators request that this implementation have further discussion with the curation working group before code merge. Temporarily closing PR desired options can be explored (may possibly be more than the existing 3 options).

**Pull request closed without merging**
