### PR TITLE
Connects to #620 fix edit json

### PR DESCRIPTION
**Pull request by kilodalton**
Updates:
--Update brace npm package to current version
--Restore ability to edit json
--Remove brace/ace blockScrolling deprecation console warning
--Update deprecated cloneWithProps to React.cloneElement
--Update some additional display references (change from ENCODE to ClinGen Curation)
--Some additional python minor formatting changes recommended by flake8 linter

Testing (admins only):
--Amend an object via the edit-json route (edit+save+view in another context)
--Users list (admin-only) should show "ClinGen Curation Users"

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen Please test this branch in the manner we discussed while investigating this problem.

**Comment by jimmyzhen** [comment]
@kilodalton, I tested your branch in my local instance and have verified that I could edit/save changes to the JSON object. And there were no console warnings incurred in the process. Thank you for the fixes.

**Comment by kilodalton** [comment]
@jimmyzhen Thanks for testing.

**Comment by kilodalton** [comment]
Merged #620.

**Comment by kilodalton** [comment]
[Comment required by waffle for still open ticket #620]

**Pull request merged**
