### PR TITLE
Connects to #442. Fixed modal box Cancel button in IE.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR is for fixed the issue in which clicking "Cancel" button in the modal box fails to dismiss modal box in IE11/Win7.

Testing for #442:

1. Go to any existing GDM.
2. Click on "Add New PMID(s)" button or the "Add" (or "Edit") link next to the OMIM ID label.
3. Click on "Cancel" button in modal box.
4. The expected result is that the modal box will be dismissed.

### CODE REVIEW

**Comment by kilodalton** [comment]
This solution removes the bug fix for #144 in and PR #270 (bug: Return closes PMID/OMIM modal).

Using current branch, hitting Return closes modal on Mac and Win without taking any action  (i.e. does not submit, and just closes modal, thus is not desired). Hitting Return should either do nothing or Submit.

An alternate solution other than changing the below needs to be investigated.
`if (e.type == 'click'){`    to `if (e.detail >= 1){`

**Comment by jimmyzhen** [comment]
*(Updated)* New changes had been included in this PR to address the following issues:
1. Removed code that intends to prevents the enter/return key from dismissing the modal box, which pressing the enter/return key is treated as a click event in the context of a form.
2. Clicking the "Cancel" button in the modal box will dismiss it in IE11/Win7 as well as Chrome/Firefox on Mac OS X.
3. Pressing the enter/return key in the modal box will attempt to submit the form (similar to a common form behavior), with the user-provided PMID/OMIM ID strings.
4. On the Provisional pages, pressing the enter/return key will attempt to submit the form, while clicking the "Cancel" button will take the user back to the previous page as intended.

Testing steps for #442 

_For "Cancel" button behavior in modal box_
1. Go to any existing GDM.
2. Click on "Add New PMID(s)" button or the "Add" (or "Edit") link next to the OMIM ID label.
3. Click on "Cancel" button in modal box.
4. The expected result is that the modal box will be dismissed.

_For Enter/Return key behavior in modal box_
1. Go to any existing GDM.
2. Click on "Add New PMID(s)" button or the "Add" (or "Edit") link next to the OMIM ID label.
3. Click in the text input field in modal box, and press the Enter/Return key.
4. The expected results are either that the form is successfully submitted and modal box is dismissed, or the form fails to be submitted due to invalid ID and modal box remains present.

_For "Cancel" button behavior on Provisional Pages_
1. Create a GDM
2. Add a PMID
3. Add a proband individual (ind001) with a variant (111) associated.
4. Select "Support" as the Assessment Variant, and submit the form. Then expect to see a "Generate Summary" button at the upper right hand corner on the GDM page.
5. Click on the "Generate Summary" button and you will be presented with a form on the Provisional page. Click on the "Cancel" button at the bottom of the page. The expected result is that the user will be taken back to the GDM page.
6. In cases where a summary had been generated previously, click on the "Edit Classification" link and proceed to the form on the Provisional Page. Clicking on the "Cancel" button also takes the user back to the GDM page.

image

**Comment by kilodalton** [comment]
Nice fix.

**Comment by kilodalton** [comment]
Merged #442.

**Pull request merged**
