### PR TITLE
Connects to #1094. Provisional curation scoring table

### PR DESCRIPTION
**Pull request by mrmin123**
image

Adds logic for calculating the points and displaying them in the provisional curation page.

Testing (very long and convoluted if you actually want to do everything...):

1. Create GDM (autosomal dominant vs autosomal recessive vs mitochondrial/others will have different results)
2. Add various evidence in various hierarchies (ex: lone individual, individual within family within group, etc)
3. Check scoring to make sure they coincide with rules set in #1138

### CODE REVIEW

**Comment by kilodalton** [comment]
@mrmin123 @jimmyzhen 

Please provide test conditions and expected results for various situations.

Since no automated BDD tests have been submitted with the PR it is essential to refer back to expected testing set up and results at the time the PR was submitted.

These tests  are also used during release candidate evaluation.

**Comment by mrmin123** [comment]
@kilodalton I've written very basic test instructions in the original PR. I will write out a test scenario for two of the rows on the table:

1. Create GDM w/ Autosomal Dominant MOI.
2. Create a Group. Create a Family within the Group. Give it a Proband by adding a Variant and the necessary Proband Individual information. Also specify LOD score information and have it set to be included in final calculations.
3. Go View/Assess the created Proband Individual and give it a Score. Specify 'Variant is de novo'.
4. Go view Provisional Classification. Ensure that for row 3 the count is 1, and that Points are whatever score you gave it. Ensure that for row 6 the count is 1, the LOD score shows up properly in the parenthesis, and that the LOD score converts properly to the Segregation Points using [this scale](https://github.com/ClinGen/clincoded/issues/1138#issuecomment-266814416).

Again, to be thorough, repeat this around 12 to 15 times (depending on MOI) for each row and Proband/Case-Control/Experimental type (including subtype!), and then repeat it all over again to ensure that the points are added correctly/to ensure evidence counts are being counted properly/to make sure that the max scores for each right-side column category works properly (taken directly from code):
```
+        VARIANT_IS_DE_NOVO: 12,
+        PREDICTED_OR_PROVEN_NULL_VARIANT: 10,
+        OTHER_VARIANT_TYPE_WITH_GENE_IMPACT: 7,
+        AUTOSOMAL_RECESSIVE: 12,
+        SEGREGATION: 7,
+        CASE_CONTROL: 12,
+        FUNCTIONAL: 2,
+        FUNCTIONAL_ALTERATION: 2,
+        MODELS_RESCUE: 4,
+        GENETIC_EVIDENCE: 12,
+        EXPERIMENTAL_EVIDENCE: 6,
+        TOTAL: 18
```
then either edit/add new ones to ensure that custom scores work properly (including 0s, which are broken right now, and will be addressed in #1191 ), and to ensure that contradicts/other none-'Score' type scoring is not counted. Repeat all of above for Autosomal Recessive which does not allow for scoring in rows 1-3, but in 4-5 (this is reversed for Autosomal Dominant), and Mitochondrial/another one, which allows scoring in all rows 1-5.

That said, I'm not going to write out all the steps for the above, and hopefully it's evident as to why...

Sidenote: I did ask the curators to stop testing on the instance for this because all of this code is getting ripped apart and merged elsewhere in #1184.

**Comment by jimmyzhen** [comment]
@mrmin123, thank you for providing the test cases and the expected behaviors.

@kilodalton, I also want to point out that, in order to score a **Proband**, there are only 3 MOIs that really matter -- `Autosomal dominant inheritance`, `Autosomal recessive inheritance` and `X-linked`.

While both `Autosomal dominant inheritance` and `X-linked` MOIs would return 3 _Case Information_ types -- `Variant is de novo`, `Proband with predicted or proven null variant` and `Proband with other variant type with some evidence of gene impact`, the `Autosomal recessive inheritance` MOI would only return 2 _Case Information_ types -- `Two variants in trans and at least one de novo or a predicted/proven null variant` and `Two variants (not predicted/proven null) with some evidence of gene impact in trans`.

As a result, we are **not** expecting to be able to score the Case-Level Proband on all 5 _Case Information_ types for any given MOI within the context of one individual GDM.

I think the Case-Level Proband scoring can be alternatively tested by creating various individuals (e.g. associated with group/family or standalone, Proband or not) from multiple annotations within one single GDM. By scoring all the Proband individuals on different _Case Information_ types, you will have better picture of how the points are counted.

**Comment by kilodalton** [comment]
Merged #1094.

**Comment by kilodalton** [comment]
[pls ignore: comment added to show PR on waffle]

**Pull request merged**
