### PR TITLE
Connects to #95. Dashboard page

### PR DESCRIPTION
**Pull request by mrmin123**
http://localhost:6543/dashboard/
image

### CODE REVIEW

**Comment by mrmin123** [comment]
New look for http://localhost:6543/dashboard/ :
image

**Comment by selinad** [comment]
Hi Min,

Were you able to get the history to sort chronologically?  I know there was a problem with the sorting, but it looks like you may have resolved it?

Where you have the words "In Process," it should still say "Status" (sorry if I confused you - I was talking about the values for Status (I am working with Kang on those).

For the PMIDs - those are such long links - probably OK for now, but I'd like to think of something simpler.  Maybe **PMID:NNNN** added to DICER1-Achondroplasia (*Autosomal dominant inheritance*) where only the PMID is linked (bolded here only to represent hyperlink).  This might help make the fact a PMID was added more obvious.  If it's easy, you could try.  If not, no worries.

I think that PMID:NNNN has no spaces in it throughout rest of database - we would want to be consistent with other uses, so just double check that.

Will the list of Gene-Disease records link under Tools go to the list of GDMs for all curators?  If so, it just occurred to me that maybe we should add the word "all" before "Gene-Disease..." to that link.

For consistency, I might now say "Your Recent History" (add "Your") - the Tools are universal and we use "Your" for the Gene-Disease Records.

**Comment by mrmin123** [comment]
* The history should sort correctly now, although old data before correct timestamps were added will still behave strangely.
* I'll change it 'In Process' back to 'Status'
* I saw PMID: NNNN (with space) in curation central, so went with the same style. Would you prefer without?
* I will look into this.
* The 'View Gene-Disease Records' link under Tools currently go to this address: http://95-mc-dashboard-page-4a95238-minchoi.instance.clinicalgenome.org/gdm/ ; everything is visible
* I'll add 'Your' to 'Recent History'

**Comment by selinad** [comment]
* Excellent re sorting
* Super
* I see PMID:NNNN on the Group box Forrest had - I prefer without the space
* lets add "all" to that View link since it goes to all
* Thanks for adding "Your"

**Comment by mrmin123** [comment]
Incorporating above changes:
image

**Comment by selinad** [comment]
Hi Min,

Looking good. One typo (new "Youe" should be "Your" ;-))

Just noticed that "added" appears twice for PMID rows (oops).  I think a simple solution for now would be to put a semicolon after the mode of inheritance for all rows:

e.g.

PMID:NNNN added to *........with paternal imprinting)*; *added blah*

DICER1-Achondroplasia............; *created blah*

**Comment by selinad** [comment]
2 more quick things:
* what do you think of bolding the G-D
e.g. PMID:NNNN added to **DICER1-Achondroplasia** (*Autosomal dominant*); *added 2015...*
* Before, were Status and Creation date in bold and the value in regular?

**Comment by mrmin123** [comment]
Thanks for catching that spelling error :)
The 'added' twice does look weird, but does look a bit better with the semicolon:
image

**Comment by mrmin123** [comment]
How does this look?
image

**Comment by selinad** [comment]
Nice!  We will want to do some stylistic things for 1.0 (remove bullets, add spacing, etc.), but its functionality is correct and it looks clean enough for 0.5.  Thanks, Min!

**Comment by kilodalton** [comment]
Merged #95

**Pull request merged**
