### PR TITLE
Connects #674 kl schema interpretation, transcript and protein

### PR DESCRIPTION
**Pull request by kgliu0101**
Changes:
1. Added 3 new schema files, interpretation.json, transcript.json and protein.json, in `src/clincoded/schemas/`.
2. Added classes and functions in `src/clincoded/types/__init__.py` to control relationships.
3. Added related test data files, interpretations.json, transcript.json and protein.json, in `src/clincoded/tests/data/inserts/`.
4. One interpretation in test data has provisional array for set interpretation status to "Provisional".
5. Added standard_status in mixinProperties in 3 schema files above.

View test data:
* type "localhost:6543/interpretations", "localhost:6543/transcripts", or "localhost:6543/proteins" in url, and then select one in list.

### CODE REVIEW

**Comment by jimmyzhen** [comment]
@kgliu0101 Your implementation of the interpretation schema and test data are working well for what I need in the development of the Variant Curation Evidence Hub so far. Thank you very much!

**Comment by kilodalton** [comment]
Current Observations regarding minor additional changes (in addition to other previous items mentioned in Slack which have already been addressed in the current version being reviewed [addressed items include: missing system status, typos, text regarding reference to external resources]):
--ORPHA numbers: 
Orphanet representations should be all caps, e.g. ORPHA79452 , not Orpha79452
(see: http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4/ `"interpretation_disease": "Orpha79452",`)

in `src/clincoded/types/__init__.py`:
- `return 'Orpha' + disease[10:-1]`
should be 
- `return 'ORPHA' + disease[10:-1]`

--Typos
- "Interpretatoin Status" should be  "Interpretation Status" in `src/clincoded/schemas/interpretation.json`
- "List of Transcript" should be "List of Transcripts" in `src/clincoded/types/__init__.py`
- "List of Protein" should be "List of Proteins" in `src/clincoded/types/__init__.py`

**Comment by kgliu0101** [comment]
"Orpha" is changed to "ORPHA". Typos are corrected.

**Comment by kilodalton** [comment]
View/select test data:
- http://localhost:6543/interpretations 
- http://localhost:6543/transcripts
- http://localhost:6543/proteins

**Comment by kilodalton** [comment]
Merged #674.

**Pull request merged**
