### PR TITLE
Connects to #871. Connects to #860. Connects to #854. Connects to #823.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR primarily consists of commits pertinent to change requests in both #860 and #871.

**Technical details:**
1. A new `clinvar_interpretations.js` file has been created to only include 2 helper methods used to fetch/parse ClinVar RCV data for the display of ClinVar Interpretations table on the Basic Information tab.
2. To fetch condition data for individual ClinVar RCV IDs, a second API call (to ClinVar) is required given the parsed RCV IDs from the initially parsed ClinVar variant data.
3. Karen had suggested an alternative API (e.g. http://myvariant.info/v1/query?q=RCV000049262&fields=clinvar.rcv) by myvariant.info because the response appears to have the same RCV condition data and it is already in JSON format. However, after another closer, we discovered that the response does not include all associated conditions for any given RCV ID. Rather, it only includes one condition. I suggested to Matt that he and Karen should get in touch with the myvariant.info team in this regard. Then we can switch to use myvariant.info from ClinVar for the second API call in the future when all conditions are included in the response.

**Steps to test:**
1. Login and use 55847 for the variant ID at the selection interface.
2. Proceed to the Basic Information tab.
3. Expect to see the previously named "ClinVar Transcripts" table now being renamed to "RefSeq Transcripts".
4. Expect to see a new "Exon" column added to the "ClinVar Primary Transcript", "RefSeq Transcripts", "Ensembl Transcripts" tables.
5. Expect to see the "RefSeq Transcripts" table being populated with RefSeq transcript data in the same format as seen in the "Ensembl Transcripts" table.
6. Expect to see the "ClinVar Primary Transcript" table also displaying Exon data.
7. Expect to see "* Canonical transcript" notes in the headers of "RefSeq Transcripts" and "Ensembl Transcripts" tables. And expect to see "*" indicators in the rows that are canonical transcripts in their respective tables.
8. Expect to see a new "ClinVar Interpretations" table added to the top of the Basic Information tab. And expect to see relevant RCV data being displayed in the table, as well as clicking on individual links in this table will open up new windows to the intended destinations.

### CODE REVIEW

**Comment by jimmyzhen** [comment]
@kilodalton While my local browser and JavaScript tests passed, the Travis tests repeatedly failed. Can you advise me what I/we can do to move forward with the tests? Thanks!

**Comment by kilodalton** [comment]
@jimmyzhen Temporary connection/tunnel problem directly from TravisCI to Sauce Labs -- not related to our code. If the test passes BDD locally and fails the Chrome test on Travis this is often the case.  I restarted the test and it passed. Thanks for the heads up.

**Comment by jimmyzhen** [comment]
Thank you, @kilodalton!

**Comment by kilodalton** [comment]
@jimmyzhen 

ClinVar shows the Clinical Significance before Review Status  on both the variation and RCV views.

Variation ID: 55847
http://www.ncbi.nlm.nih.gov/clinvar/variation/55847/

image

http://www.ncbi.nlm.nih.gov/clinvar/RCV000175486/

image


I think in the table form it might make sense to show in that order as well (people are looking for that bit of info first). 


Can you give an estimate of the time it would take to just swap those two columns?

Currently:

image



@selinad @wrightmw Please indicate if you are OK with switching the columns.

**Comment by jimmyzhen** [comment]
@kilodalton Swapping the 2 columns would take just a few minutes.

**Comment by kilodalton** [comment]
@jimmyzhen Thanks for the info. Please go ahead and change the order of those two columns since it is a quick change and will align us with the ClinVar (web) representation.

**Comment by selinad** [comment]
FYI - My thought is we don't have to be perfectly aligned with ClinVar's presentation but should do what is most intuitive for the user (this particular situation is a bit different from ExAC).  What is the order after the change?  I'd rather have Review Status as it was or after Disease, as @wrightmw had specified, so that the clinical significance and the disease are together.

**Comment by kilodalton** [comment]
@selinad I did not see in the chat status where the location of Review Status had been specified. It appeared to be the last column added in the ticket without comment.

The new proposed order which would be more in line with ClinVar (as shown in the screenshots above) would be: 
"Reference Accession"	"Clinical Significance" "Review Status" "Disease [Source]"

**Comment by selinad** [comment]
@wrightmw worked it out with @jimmyzhen and I.  As I mentioned, I don't think we need to be aligned with ClinVar, I think we need to do what makes sense for our users according to our understanding as biocurators.  

We were in a meeting, so did not have a chance to indicate whether we were in support of the change (I see you had asked).  It's fine for this release - @wrightmw and I will discuss and see if want to change it in the future.

**Comment by kilodalton** [comment]
@selinad The column change has not been implemented. Since there has been a general push in many other places to make our interface reflect external data sources (ExAC, etc, etc) in many other places on the interface it seemed like a reasonable quick change and I pinged Jimmy (not on github) before you responded that you may be chiming in.

**Comment by selinad** [comment]
Sorry, I thought it had been changed since you asked him to do so and then the checks, etc. came through.  If it hasn't been changed, my vote is to leave it as is, but @wrightmw can weigh in.

**Comment by kilodalton** [comment]
Merged #871. Merged #860. Merged #854. Merged #823.

**Comment by kilodalton** [comment]
[Comment added to PR to refresh Waffle display of PR attached to ticket]

**Pull request merged**
