### PR TITLE
Connects to #544, Connects to #514, Connects to #546, Connects to #542, Connects to #471, Mutalyzer link and text

### PR DESCRIPTION
**Pull request by kgliu0101**
Tickets #514, #544, #546, #542 and #471.

**Change related to #542**
Add a warning for not using real name in individual page.
summary

**Change related to #546**
Use html entity "&#8804" to replace "&#10877".
summary

**Change related to #544 and #514**
Add a text with hyperlink to Mutalyzer.com in family, individual and experimental pages.

**Test for #544 and #514**
* Create a GDM,
* Add a PMID,
* Add a family and click "Add variant associated with individual" button. Expect to see "(e.g. HGVS, RCV, refSNP (rs) ID). For help in verifying, generating or converting to HGVS nomenclature, please visit Mutalyzer". 
* Click "Mutalyzer", expect to direct to https://mutalyzer.nl/ at a new tab.
* Click Cancel.
* Add an individual, expect to see the same text and link.
* Add experimental (Expression Type B, Functional Alternation, Model System and Rescue), expect to see the same text and link.

**Change related to #471**
Add a note for Contradict assessment in provisional page

**Test for #471**
* With small group test data loaded, go to ../curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586.
* Select PMID 8078586.
* Change assessment of FamilyBBB to Contradicts, save.
* Generate a new summary, expect to see a red message as:
summary
* Click Cancel.
* Change the assessment of FamilyBBB to any other value, save.
* Generate a new summary, expect to see the message no longer existing.
* Click Cancel.
* Change assessment of variant 26485 to Contradicts, save.
* Generate a new summary, expect to see the same message.
* Click Cancel.
* Change the assessment of the variant to any other value, save.
* Generate a new summary, expect to see the message no longer existing.
* Click Cancel.
* Change assessment of Experimental 1 to Contradicts, save.
* Generate a new summary, expect to see the same message.
* Click Cancel.
* Change the assessment value to any other, save.
* Generate a new summary, expect to see the message no longer existing.

### CODE REVIEW

**Comment by kgliu0101** [comment]
Ticket #471 (Add note for Contradict assessment) is include in this one.

**Comment by kilodalton** [comment]
Merged #544. Merged #514. Merged #546. Merged #542. Merged #471.

**Comment by kilodalton** [comment]
Note: Variant 26485  does not exist in the testing steps described for "Test for #471" as indicated above (URL: + "/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586") . Variant 55966 may be used instead.

**Comment by kgliu0101** [comment]
It should be variant 36485

**Pull request merged**
