### PR TITLE
Connects to #89. Experimental Data curation page

### PR DESCRIPTION
**Pull request by mrmin123**
* Added experimental data curation page (excluding Assessments; see #337)
* Added relevant experimental data information to Dashboard and Curation Central
* Expanded forms.js to support checkboxes
* Updated schema (spelling corrections and text changes)

Testing:
1. Create GDM
2. Add PMID
3. Add Experimental Data one of each Experimental Data type (two for Biochemical Function and Expression: one for A subtype, one for B subtype)
4. Confirm that the Variants panel DOES NOT exist for Biochemical Function, Protein Interaction, and Expression subtype A
5. Confirm that the entries show up correctly in Curation Central (including associated Variants)
6. Confirm that the entries show up correctly on Dashboard
7. Check Edit pages for these Experimental Data entries
8. Check View pages for these Experimental Data entries

### CODE REVIEW

**Comment by kilodalton** [comment]
@mrmin123 

In smaller browser window (width-wise) text is sometimes cut off from Return to Curation page button:
image

To reproduce: reduce and expand browser width on the page after experimental data is added

**Comment by kilodalton** [comment]
On the view page, if a boolean value is the result of a checkbox, the description would ideally not be in the form of a question:

image

It would make more sense for it to say:

This gene or genes have been implicated in the above disease:   true/false

(instead of "Has this gene or genes been implicated in the above disease:	true)

**Comment by mrmin123** [comment]
@kilodalton 
I've fixed the button text overflowing:
image

As for the text change(s) lets hold off on those because @selinad mentioned that there will be additional text changes that will have to be done.

**Comment by kilodalton** [comment]
@mrmin123 Looks good. Thanks for the change on the button and making the additional ticket for future text changes.

**Comment by kilodalton** [comment]
Merged #89

**Pull request merged**
