### PR TITLE
Connects to #1169. LOD Calculation for Family Curation

### PR DESCRIPTION
**Pull request by mrmin123**
Note: several outstanding bugs are outlined and will be addressed with #1177

image

Implements formulas for calculating LOD scores for Autosomal Dominant and Autosomal Recessive GDMs in the Family Curation page. The field only locks and calculations done automatically for Families in GDMs that fit the above two MOI. Other fields retain the ability for the user to edit the field. 

When the user does not have an entered LOD score (Estimated or Published), regardless of MOI (automatically generated LOD score or not), the dropdown to include the LOD score in final calculations become disabled:
image

If the user input/generated a LOD score, then selected an option for the LOD score inclusion dropdown, then cleared the LOD score, the LOD score inclusion dropdown also resets.

Testing:

1. Get to the GCI's Family Curation page for a GDM w/ Autosomal Dominant MOI
2. Enter values into the 'For Dominant AND Recessive:
Number of AFFECTED individuals WITH genotype?', 'For Recessive Only:
Number of UNAFFECTED individuals WITHOUT the biallelic genotype?', and 'Number of segregations reported for this Family' fields
3. Set 'Published LOD score' to 'No' and verify that the value in the field and the dropdown below it behave as expected.
4. Change values for fields in step 2 and verify that fields in step 3 work as expected.
5. Repeat steps 2~4 for GDM w/ Autosomal Recessive MOI
6. Repeat steps 2~4 for GDM w/ MOI that is neither of the above

Example scores:
screen shot 2016-11-11 at 2 45 21 pm

### CODE REVIEW

**Comment by kilodalton** [comment]
Merged #1169.

**Comment by mrmin123** [comment]
(Comment to show on Waffle)

**Comment by selinad** [comment]
Adding this to make certain documented -- scoring was implemented using this.
screen shot 2017-01-13 at 5 50 38 pm

**Comment by selinad** [comment]
Note to self: works great in AD record...need to test in AR

**Pull request merged**
