### PR TITLE
Connects to #539. Fixed button display in narrow viewport.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR is to address the problem in which the buttons are overlapping the text on the form submission confirmation page in narrow viewport.

**Testing steps for #539:**
1. Go to the Curation Central page and add a new PMID.
2. Proceed to the Family Curation page by clicking on the blue "Family" bar on the far-right column.
3. Fill out the form and click "Save" to submit it.
4. On the subsequent confirmation page, on where there are 3 buttons (e.g. **Edit proband Individual**, **Add non-proband Individual**, and **Return to Record Curation page**), reduce the browser window width to less than 767px.
5. You should expect to see that the buttons are no longer overlapping the text above it.

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen 

Still has a glitch at intermediate widths

wide (ok):
752x337
image


intermediate problem (slight display problem):
The suitcase icon is wider than the text box:
618x396
image

narrow (looks Ok):
Looks OK again at 546x493
image

**Comment by jimmyzhen** [comment]
@kilodalton Sorry that I missed it. I will fix it today.

**Comment by jimmyzhen** [comment]
@kilodalton I've committed new CSS changes to this PR. Let me know if you have any questions. Thanks.

**Comment by kilodalton** [comment]
Looks good. Thanks for the update.

**Comment by kilodalton** [comment]
Merged  #539.

**Comment by kilodalton** [comment]
[Comment required by waffle for still open ticket #539]

**Pull request merged**
