### PR TITLE
Connects #581 variant hover preferred title

### PR DESCRIPTION
**Pull request by kgliu0101**
Following ticket #575, this ticket display ClinVar preferred title in curator palette and view pages.

**Changes**
- Add handling code to display preferred title in curator palette in curation central page
- Add handling code to display preferred title in family/individual/experimental view pages.

**Test Steps**
- Create GDM, add a PMID, add a new family, name Family010, enter variation ids 90973 and 9492, name proband Ind011, enter a Orphanet id, click Save. Go to curation central page and expect to see "Variants: 2" under Family010 and Ind011 in curator palette. And 2 preferred titles are shown in a pop-out window when mouse cursor is hover blue colored and underlined "2". 
screen shot 2016-02-06 at 12 37 51 am
- In addition, 2 preferred titles (or its left part with ellipses if too long) are shown in Associated Variants.
screen shot 2016-02-06 at 12 48 26 am
- Click the titles, expect to redirect to variant curation page.
- Go back to curaion central page by clicking Cancel in variant curation page. View Family010, expect to see preferred titles shown as
screen shot 2016-02-06 at 12 53 18 am
- Go back to curation central page and View Ind011, expect to see the same titles.
- Go back to curation central page and add a new experimental, name ExpAAA, select Rescue/Patient, cell, enter data in every required field, enter variation ids 55966, 55996, 55942 and enter "some description here" in Other description field, save. At curation central page, expect to see
screen shot 2016-02-06 at 1 04 46 am
- View ExpAAA, expect to see 4 associated variants
screen shot 2016-02-06 at 1 06 07 am

**End of Test**

### CODE REVIEW

**Comment by kilodalton** [comment]
@selinad @wrightmw 
I brought up an instance from Kang's branch... you can evaluate the changes for this ticket at:
https://581-preferredtitle-in-paletter-d906771-karen.demo.clinicalgenome.org

**Comment by selinad** [comment]
Hi @kgliu0101 - works very well - excellent! 

Confused by one thing - why 55942 thrown in there?  Shouldn't it return the CV Preferred Title?

Should I make new ticket for next release for changing wording of "Other Description?"  thanks!

**Comment by kgliu0101** [comment]
Variant 55942 doesn't have preferred name. That is designed for test.
screen shot 2016-02-07 at 9 23 59 am

**Comment by selinad** [comment]
http://www.ncbi.nlm.nih.gov/clinvar/variation/55942/

**Comment by selinad** [comment]
@mrmin123 functionality with the modal window will take care of this, I think.  If there is no VariationID, will return that info to curator - should have no reason to display a VariationID (please correct me if I am wrong; also, perhaps you already took this into consideration).

**Comment by kilodalton** [comment]
There are several concerns with the current branch (the BDD tests fail, there are extra files in the PR, and because of concurrent work being done there will be significant merge conflicts). @jimmyzhen will evaluate what parts can put in a new branch starting fresh from the dev branch. After discussing code status with JZ, I am closing this PR (will re-open if it turns out to be more expedient to use this branch instead of using relevant code in a fresh branch).

**Pull request closed without merging**
