### PR TITLE
Connects to #540. Update HPO messages

### PR DESCRIPTION
**Pull request by mrmin123**
Experimental page:
image

Family:
image

Individual:
image

### CODE REVIEW

**Comment by selinad** [comment]
Great - except I think I had written "feature(s)"

**Comment by mrmin123** [comment]
@selinad That you did.. I'll change it for both Family and Individuals

**Comment by mrmin123** [comment]
Family:
image

Individual:
image

**Comment by selinad** [comment]
Looks great!  Thanks @mrmin123 !

**Comment by kilodalton** [comment]
Merged #540.

**Pull request merged**
