### PR TITLE
Connects to #47 reenable elasticsearch

### PR DESCRIPTION
**Pull request by mrmin123**
Removed "boost_values" entries from JSON, and removed human_donors, publication, software, and software-version objects and related references. Re-enabled elasticsearch tests.

### CODE REVIEW

**Comment by mrmin123** [comment]
Some working links:
http://localhost:6543/search/?type=gdm
http://localhost:6543/gdm/9ffd7c1e-16d9-11e5-b283-60f81dc5b05a/

**Comment by mrmin123** [comment]
Not directly related but tangential so I went and attempted to address #60 and #74 as well (the fix for these are related). Replaced ENCODE-related objects with ClinGen ones. List of objects that show up and their naming needs review, however.

**Comment by forresttanaka** [comment]
With this branch, I did a search that would be typical from the /create-gene-disease/ page and it found the one unique matching record, where before this change it would find nothing. The search here is:

http://localhost:6543/search/?type=gdm&gene.symbol=FANCM&disease.orphaNumber=84&modeInheritance=Other

And it came up with this object, which is correct:

http://localhost:6543/gdm/08bc9bcc-16da-11e5-86d6-60f81dc5b05a/

So my code can absolutely use this.

screen shot 2015-07-09 at 17 26 01

**Comment by mrmin123** [comment]
Great! I should have linked this earlier, but please also check the default search page to see if the expected output is generated:
http://localhost:6543/search/
Thanks

**Comment by kilodalton** [comment]
Merged #47

**Pull request merged**
