### PR TITLE
Connects to #288. ReactJS 0.14 upgrade with recent dev commits.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR consists of the changes pulled from Forrest's react 14 upgrade branch (https://github.com/ClinGen/clincoded/compare/288_ft_react_14) and the recent commits merged into the dev branch.

Testing for #288:

In general, various functionality shall be tested throughout the entire site.

According to Forrest:
> Testing should include that everything works properly when you log in and log out — most of the changes that I felt very vague about their effects have to do with that. The other widespread change has to do with getting form values — the 0.14 method changed, and it’s an easy change. But it did affect code kind of all over. Look to see that what you entered on forms is the value that ends up in the objects — generally the View pages and editing objects should expose any problems here.

> A past problem that caused the checkbox failure in Experimental Data had to do with mutating the React props inside a component. That was never proper in React but you could get away with it before 0.14. But React 0.14 throws a JS error if you try to do that. I’m pretty sure only the Experimental Data module did that, so I doubt that’s anything to check for generally.

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen (please consult with @forresttanaka if you need assistance)

Running locally on Chrome

Weird thing when going to assess variants...

Curate Variant page is blank:
image

image

Uncaught TypeError: Cannot read property 'currentVal' of undefined
:6543/static/build/bundle.js:60189 OBJECT LOAD ERROR: undefined — undefined
:6543/static/build/bundle.js:42520 Uncaught TypeError: Cannot read property 'resetValue' of undefined
:6543/static/build/bundle.js:57011 persona ready


Clicking on dashboard icon from that blank page I see:
"Cannot read property 'resetValue' of undefined"

image


assessment.js:213 Uncaught TypeError: Cannot read property 'resetValue' of undefinedmodule.exports.AssessmentPanel.React.createClass.componentWillReceiveProps ....



To make sure weirdness wasn't just with the new-ish setup on the laptop:
on 
https://288-jz-react-14-dev-merged-d2d4581-jzhen.demo.clinicalgenome.org/family-curation/?gdm=2e99d635-cb5b-40e1-8aa8-46a64d4892d4&evidence=e223a4c3-0575-473e-bc77-2043fe3a86b4&group=045e7a4c-a3d7-4bd3-bc2c-469235693eac

Using Safari
Trying to add proband indiv to family

There is no place to put indiv name:
image


When you start typing in the variant ID, a big grey space appears on Safari

image


I realize we direct people towards Chrome... but can you see if you can reproduce some of these things?

**Comment by kilodalton** [comment]
Also in general seeing more warnings than in the past:
image

**Comment by jimmyzhen** [comment]
@kilodalton Thanks for catching these issues. I will look into in the morning and consult with Forrest if needed.

**Comment by mrmin123** [comment]
> There is no place to put indiv name:

I ran into this on my current dev branches and the fix was to take the disappearing divs out of the `clearfix` divs they're nested in.

**Comment by jimmyzhen** [comment]
`The setState(...)` warnings appear to be more amplified in ReactJS 0.14, while they are less so in the current version. For example:
image

I have addressed the `validateDOMNesting(...)` warning in my local branch. Will deal with the `The setState(...)` warnings as well.

**Comment by jimmyzhen** [comment]
@kilodalton Given the `setState(...)` warnings are pertinent to the Dashboard component, I have found the "componentWillReceiveProps" Lifecycle method being the culprit in the component:
```
componentWillReceiveProps: function(nextProps) {
    if (nextProps.session.user_properties) {
        this.setUserData(nextProps.session.user_properties);
        this.getData(nextProps.session);
    }
    this.getHistories(this.props.session.user_properties, 10).then(histories => {
        if (histories) {
            this.setState({histories: histories});
        }
    });
},
```

In particular, both of the `this.getData(nextProps.session)` and `this.setState({histories: histories})` calls are the reasons for the warnings as they appear to be fired at the time of unmounting the component.

Based on the following suggestion provided at https://facebook.github.io/react/blog/2016/01/08/A-implies-B-does-not-imply-B-implies-A.html:

> As a result, your implementation of componentWillReceiveProps MUST NOT assume that your props have changed. If you want an operation (such as a network request) to occur only when props have changed, your componentWillReceiveProps code needs to check to see if the props actually changed.

I have modified the "componentWillReceiveProps" Lifecycle method to be the following:
```
componentWillReceiveProps: function(nextProps) {
    if (nextProps.session.user_properties && nextProps.session.user_properties != this.props.session.user_properties) {
        this.setUserData(nextProps.session.user_properties);
        this.getData(nextProps.session);
        this.getHistories(this.props.session.user_properties, 10).then(histories => {
            if (histories) {
                this.setState({histories: histories});
            }
        });
    }
},
```

That seems to have resolved the warnings while the UI continue to work as expected. Please let me what you think. Thanks.

**Comment by kilodalton** [comment]
Nice work, tracking it down and resolving the various issues. Please include include also the clearfix solution @mrmin123 suggests and test against Safari even though technically is an existing problem not part of the upgrade.

**Comment by jimmyzhen** [comment]
Turns out that the family_curation and experimental_curation components are already using similar techniques to prevent setState(...) being fired at the time of unmounting the component. For example:
`if (typeof nextProps.session.user_properties !== undefined && nextProps.session.user_properties != this.props.session.user_properties)`

So I will just use that and keep it consistent in the dashboard component.

**Comment by jimmyzhen** [comment]
@kilodalton In regards to the display of **Individual Name** field on the family curation page, as you start entering a value in the **ClinVar VariationID** input field, the **Individual Name** field would be displayed.

This behavior may not be associated with Safari or the "clearfix" solution @mrmin123 had implemented for https://github.com/ClinGen/clincoded/commit/34492159d0a756e40af6d310414beed86bcb2e3d#diff-4b373df8704f08ac7a58298d7434f363.

In fact, this behavior appears to be "by design" in the family_curation component in which the individual name field is intended to be hidden unless the expected conditions are true (e.g. https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/static/components/family_curation.js#L1560).

Furthermore, I have verified that this behavior is consistent in Safari, Chrome, Firefox and IE11.

**Comment by jimmyzhen** [comment]
The latest commits have addressed the various console warnings due to the react 14 upgrade.

One of the fixes is wrapping the <tr> tags with <tbody> tags, and this fix has incurred many lines of changes due to indentation.

**Comment by kilodalton** [comment]
@jimmyzhen I can show you on my machine tomorrow. I can't add an individual name for the proband individual for a family on Safari...and there is a "Please fix errors on the form and resubmit." if I try to save because some fields are required are not being displayed. Like individual name.

**Comment by kilodalton** [comment]
Update: Only difference I can see  between machines where bug is not evident is small version difference in Safari:
Works: Version 9.0.2 (11601.3.9)
Can't enter indiv name: Safari 9.0.3

**Comment by jimmyzhen** [comment]
Hi @kilodalton,

After addressing various console errors and bugs due to the ReactJS v0.14 upgrade, as well as merging Min's latest fixes from this week, the branch is finally in a good shape and ready for code review.

Unfortunately this has taken more time than I thought, and the curators have yet to review the final version of the react 14 branch, so I am hesitant to rush Min to merge the PR on the last day of the week.

Since you will be back next week, would you mind review this PR? Thank you.

**Comment by kilodalton** [comment]
@jimmyzhen I will review on Monday.

**Comment by kilodalton** [comment]
Merged #288.

**Comment by kilodalton** [comment]
[Comment required by waffle.io to keep PR displayed on board for still-open ticket #288]

**Pull request merged**
