### PR TITLE
Connects to #181 ft genotyping bug

### PR DESCRIPTION
**Pull request by forresttanaka**
* When a new Group Curation page comes up, the Method 2 genotyping method dropdown should be disabled. Making a selection from Method 1 should then enable the Method 2 dropdown.
* When an existing Group Curation page is edited and no entry was made in the Method panel at all before, then both the Method 1 and Method 2 dropdowns should show “Select,” and the Method 2 dropdown should be disabled.
* When an existing Group Curation page is edited and an entry aside from the Method 1 and Method 2 dropdowns was made in the Method section, then both the Method 1 and Method 2 dropdowns should show “Select,” and the Method 2 dropdown should be disabled.
* When an existing Group Curation page is edited and an entry had been selected in Method 1, the Method 2 dropdown should come up enabled, with “Select” as the current option.
* When an existing Group Curation page is edited and both the Method 1 and Method 2 dropdowns had been selected, they should both be enabled and their previous selections selected.

### CODE REVIEW

**Comment by selinad** [comment]
Sounds good.  When editing, what happens if the user puts Method 1 to Select and Method 2 already has a choice?

**Comment by selinad** [comment]
What happens when editing and both 1 & 2 have values, then user changes Method 1 to Select?

**Comment by forresttanaka** [comment]
You can’t do that right now; once you choose something other than Select, you can’t go back. That will need to change, and then we have to decide what happens in the case you mention. I don’t know what the right answer is there.

**Comment by selinad** [comment]
oops - sorry for duplicate - I had an error that I thought was for the first try at submitting, so did it again :P

**Comment by selinad** [comment]
You can't edit Method 1 or Method 2 right now?  Or you could edit to something in either or both, but not go have Select option?

**Comment by forresttanaka** [comment]
You can change Method 1 and Method 2, but once you move off “Select,” you can’t go back to “Select” for either one. That will be addressed in https://github.com/ClinGen/clincoded/issues/183

**Comment by selinad** [comment]
this all sounds good for now.

**Comment by kilodalton** [comment]
Merged #181

**Pull request merged**
