### PR TITLE
Connects to #827. Codon data display.

### PR DESCRIPTION
**Pull request by jimmyzhen**
This PR consists of changes pertinent to the handling of UI display in the variant codon table on the computational tab.

**Technical details:**
1. Abstracted the repetitive code from index.js and created a helper method to get HGVS notation in the formats required by either myvariant.info or Ensembl VEP.
2. Created a helper method to set the primary transcript based on the logical filtering of properties such as 'canonical', 'source' and 'hgvsc' in the Ensembl VEP response.
3. Added '&canonical=1&merged=1' params to Ensembl VEP API request to expose **canonical** flags and **RefSeq** transcripts in response.
4. Decoupled the Eutils/Esearch combo fetch method since the Esearch method for codon data relies on Ensembl VEP response going forward.
5. Updated the handling of UI display in the variant codon table given different test cases.

**Steps to test:**
Via the variant selection interface, try the following example IDs. Verify the expected display given the different test cases.

Test case 1 - Variant does not exist in ClinVar.
Expected display - **ClinVar search for this variant is currently not available.**
Example IDs: CA501097, CA501096, CA501104

Test case 2 - Protein change data, such as amino acid and/or location, not found in ClinVar.
Expected display - **The current variant is in a non-coding region.**
Example IDs: 139214, CA003323

Test case 3 - Has protein change, but ClinVar response returns count of 0.
Expected display - **No variants have been found at this codon in ClinVar.**
Example IDs: 

Test case 4 - Has protein change, and ClinVar response returns count of 1.
Expected display - **The current variant is the only variant found at this codon in ClinVar.**
Example IDs: 55847, 35824

Test case 5 - Has protein change, and ClinVar response returns count of more than 1. 
Expected display - **Additional ClinVar variants found in the same codon: count (Search ClinVar for variants in this codon)**
Example IDs: 35816, 53423

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen I push the small text change commit to your branch.

Test 4 above does not work for either variant (Example IDs: 35816, 53423). It shows:
image

**Comment by jimmyzhen** [comment]
@kilodalton Thank you for catching the bug! It's been now fixed and committed back to the PR.

**Comment by kilodalton** [comment]
@jimmyzhen Test 3 does not work for Clinvar 55847

To check the data that should be return this

image
 
image

  
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=P568%5Bvariant+name%5D+and+FOXP1&retmode=json

http://www.ncbi.nlm.nih.gov/clinvar/variation/55847/



should return "The current variant is the only variant found at this codon in ClinVar."
but instead it returns "No variants have been found in this codon in ClinVar"


It is trying to look up the wrong position:

`Object {count: 0, term: "P584", symbol: "FOXP1"}`


when it should be 
`Object {count: 1, term: "​P568​", symbol: "FOXP1"}`

from 
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=clinvar&term=P568%5Bvariant+name%5D+and+FOXP1&retmode=json

which returns  "count": "1",

**Comment by jimmyzhen** [comment]
@kilodalton Thanks for taking the time to run through the tests.

For 55847, the amino acid and position are obtained from the "RefSeq" transcript that is also flagged as "canonical" (which @wrightmw and I consider to be "primary") in the VEP response:
http://rest.ensembl.org/vep/human/hgvs/3:g.70970756G%3EA?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&domains=1&canonical=1&merged=1

In the example above, you will find 2 transcripts being flagged as "canonical" - one by "Ensembl" and another by "RefSeq". Both of these transcripts have their protein_start/protein_end properties at `584`. And so we determine the term to be `P584` given the their amino acid values.

I understand that some other transcripts from the example above have their protein_start/protein_end properties at `568`, as well as from ClinVar (e.g. http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=55847).

Is it incorrect to assume "canonical" transcript to be the "primary" transcript, or there is some discrepancy in the data returned from the APIs?

**Comment by jimmyzhen** [comment]
Hi @kilodalton,

With the latest committed changes, I have also updated the test cases information because I am adding one extra check on whether a variant exists in ClinVar.

I went through the various IDs to verify the test cases. Unfortunately, I have not been able to find an ID for the 3rd test case (as I did previously with VEP data).

**Comment by jimmyzhen** [comment]
@kilodalton,

I just talked to @wrightmw , and he said that the 3rd test case wouldn't have applied now that we are using ClinVar as the data source.

But since the check does not affect other checks and it will unlikely be invoked given our use of ClinVar for the time being, I am going to leave the 3rd test case check in there for the future.

**Comment by kilodalton** [comment]
@jimmyzhen Thx for the re-work. Looks good.

**Comment by kilodalton** [comment]
Merged #827

**Comment by kilodalton** [comment]
[Comment added to PR to refresh Waffle display of PR attached to ticket]

**Pull request merged**
