### PR TITLE
Connects to #589. Disabled curation form

### PR DESCRIPTION
**Pull request by mrmin123**
Testing:

1. Create GDM, add PMID
2. Create Experimental Data object (and assess it)
3. Assess on it with another user
4. Go to Edit page with original user (should encounter disabled form due to other user assessment)
5. Hit back button to Curation Central
6. Go to Add another Experimental Data object
7. Confirm that the form is properly editable
8. Create Family object w/ Segregation data (and assess it)
9. Assess on it with another user
10. Go to Edit page with original user (should encounter un-editable Segregation section)
11. Hit back button to Curation Central
12. Click the 'Add Family' button ONCE and confirm that you go to the Add Family page (originally, you would encounter a JS error and the link would not work on first click)

### CODE REVIEW

**Comment by mrmin123** [comment]
@selinad @wrightmw If you get the chance, please test the above at http://589-mc-disabled-curation-ed15c25-minchoi.instance.clinicalgenome.org/

Please also note that the issue with the Assessment panel not showing up sometimes is still not resolved on this branch. Refresh the page to make it show up again. Thanks!

**Comment by selinad** [comment]
@mrmin123 - sorry to be confused.  Should I be able to edit variants for Experiment 8?

http://589-mc-disabled-curation-ed15c25-minchoi.instance.clinicalgenome.org/experimental-curation/?editsc&gdm=7f9988fa-16d9-11e5-ba73-60f81dc5b05a&evidence=5cd72a73-189e-11e5-9db5-60f81dc5b05a&experimental=d06dae6b-2cb8-11e5-8e3e-60f81dc5b05a

**Comment by kilodalton** [comment]
@selinad Please don't use any pre-existing test data for this evaluation.

**Comment by selinad** [comment]
it is not relevant?

**Comment by selinad** [comment]
I'm doing both.

**Comment by selinad** [comment]
Create GDM, add PMID
Create Experimental Data object (and assess it)
Assess on it with another user
Go to Edit page with original user (should encounter disabled form due to other user assessment) :+1: 

Hit back button to Curation Central
Go to Add another Experimental Data object
Confirm that the form is properly editable :+1: 

Create Family object w/ Segregation data (and assess it)
Assess on it with another user
Go to Edit page with original user (should encounter un-editable Segregation section)
Hit back button to Curation Central
Click the 'Add Family' button ONCE and confirm that you go to the Add Family page (originally, you would encounter a JS error and the link would not work on first click)

**Comment by kilodalton** [comment]
Merged #589.

**Comment by selinad** [comment]
Everything worked except last step - clicking to add new Family did not work - did not go anywhere.  Actually, it didn't go anywhere unless I click directly on "+" - can someone else please try?

**Pull request merged**
