### PR TITLE
Connects to #49 bh fix readme

### PR DESCRIPTION
**Pull request by hitz**
This isn't perfect but it has the correct travis-ci account, doesn't mention ENCODE and reorganizes a bit.

### CODE REVIEW

**Comment by hitz** [comment]
This isn't quite ready yet, the badge isn't functioning correctly.  Tests including bdd pass on my local machine

**Comment by hitz** [comment]
OK, done with this.  Very hard to put 2 badges in an RST file

**Comment by kilodalton** [comment]
Merging even though the PR Travis test shows tests failed because there is no obvious reason for the Travis failures (a branch off of this branch [i.e. a copy] passes Travis and Sauce without a problem). There is a possibility that Travis is occasionally having a glitch when making the Sauce Connect connection to Sauce Labs for the BDD tests (i.e. occasionally the BDD tests fail on Travis but Sauce Labs is not recording any failing tests).

**Comment by kilodalton** [comment]
Merged #49

**Comment by forresttanaka** [comment]
Might be transient. You can restart the test from the test results page and maybe it’ll finish. Since the merged version worked, might be moot anyway.

**Pull request merged**
