### PR TITLE
Connects to #915 kl bug brackets no disease

### PR DESCRIPTION
**Pull request by kgliu0101**
**This PR has changes for parsing and displaying ClinVar interpretation data in Basic Info tab, including:**
 1. Only retrieve and display "primary" RCVs.
 2. Retrieve and display not only "Disease" type but also all other types of condition associated to a RCV.
 3. Add external links to HPO and MeSH. In case source name of an identifier is not "MedGen", "Orphanet", "OMIM", "HPO" or "MeSH", display identifier as "source name: id" without link since pre-set urls to external web pages are limited to the 5 sources above currently.

**Test Steps**
* Test 1 (primary RCVs)
  - In VCI, use ClinVar variant "15333" and expect to see only 4 primary RCVs (RCV000016575, RCV000016573, RCV000016574 and RCV000224000) as:
screen shot 2016-09-18 at 11 01 20 pm
Related meta data in ClinVar xml file: 
screen shot 2016-09-18 at 11 10 17 pm
xml file at: [https://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=15333](https://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=15333)

* Test 2 (Non-disease type condition)
  - Click `New Variant Curation` button at top, enter variant id "60671", click `Save and View Evidence` and expect to see ClinVar interpretation data as:
screen shot 2016-09-18 at 7 16 57 pm
Related ClinVar meta data `Type="DrugResponse"` as:
screen shot 2016-09-18 at 11 23 47 pm
in xml file [https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=clinvarset&id=RCV000054486](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=clinvarset&id=RCV000054486)

* Test 3 (Links to MeSH and HPO)
  - Click `New Variant Curation`, enter variant "13969",  click `Save and View Evidence` and expect to see identifier "MeSH" with a link:
screen shot 2016-09-21 at 1 06 50 pm
  - Click the link and expect to open a MeSH web page in a new browser tab as:
screen shot 2016-09-21 at 1 02 41 pm
  - Click `New Variant Curation`, enter variant "156411",  click `Save and View Evidence` and expect to see "HPO" identifiers with links as:
screen shot 2016-09-19 at 11 32 13 pm
  - Click a HPO link and expect to see HPO web page for relevant condition in a new browser tab.

**End of Test**

### CODE REVIEW

**Comment by kilodalton** [comment]
@kgliu0101 Why can't the MESH term be a linkout?
i.e for ClinVar variant "13969":
http://www.ncbi.nlm.nih.gov/mesh/?term=D002289

**Comment by kgliu0101** [comment]
@kilodalton Thank you for finding the url. I am going to it in.

**Comment by kilodalton** [comment]
@kgliu0101 I gave you two example URLs above, why did you use the extra parameters attached to the URL?
'%5BMeSH+Unique+ID%5D&cmd=DetailsSearch&log$=activity'

**Comment by kgliu0101** [comment]
@kilodalton 

I copied the url with `&cmd=DetailsSearch&log$=activity` at a MeSh page which is linked from ClinVar web page for RCV000015003 [http://www.ncbi.nlm.nih.gov/clinvar/RCV000015003/](http://www.ncbi.nlm.nih.gov/clinvar/RCV000015003/). This one has the same content to the one without `&cmd=DetailsSearch&log$=activity`. Thought it might be better to match whatever on ClinVar page. Sorry for forgetting note it earlier.

If it's not necessary, I'd like to change the url to `http://www.ncbi.nlm.nih.gov/mesh?term=D002289%5BMeSH%20Unique%20ID%5D`. Please let me know your comment.

Screenshot in Test 3 for MeSH link is updated. Sorry again.

**Comment by kilodalton** [comment]
@kgliu0101 You should use the minimal URL that provides all the information that you need. The additional info you are showing is more than likely only used for their internal tracking of links.  Many other sites do this. But we do not to include tracking information in our linkout.  We only need to get to a similar content display. And you have indicated that the extended link does not provide any additional content.

*Please change it to the minimal version I indicated originally and re-test.*

**Comment by kgliu0101** [comment]
@kilodalton The minimal url is `http://www.ncbi.nlm.nih.gov/mesh/?term=D002289`, right?

**Comment by kilodalton** [comment]
No. I meant don't include their tracking tags. Remove the extra pieces you added to the URL.

**Comment by kgliu0101** [comment]
@kilodalton `http://www.ncbi.nlm.nih.gov/mesh?term=D002289%5BMeSH%20Unique%20ID%5D`?

**Comment by kilodalton** [comment]
Yes. What you originally said you were going to change it back to and what I suggested originally.

**Comment by kilodalton** [comment]
Merged #915.

**Pull request merged**
